export enum Include {
    Category = "category",
    ParentCategory = "parent_category",
    SubCategories = "subcategories",
    Contact = "contact",
    Details = "details",
    DetailsDotProduct = "details.product",
    DetailsDotWarehouse = "details.warehouse",
    Payments = "payments",
    PaymentDotTransaction = "payments.transaction",
    Tags = "tags",
    Sharings = "sharings",
    RecurrencePlan = "recurrence_plan",
    ActiveEDocument = "active_e_document",
    RefundOf = "refund_of",
    FailedEInvoice = "failed_e_invoice",
    ContactPortal = "contact_portal",
    ContactPeople = "contact_people",
    Company = "company",
}
