export enum Include {
    Category = "category",
    ParentCategory = "parent_category",
    SubCategories = "subcategories",
    Contact = "contact",
    Details = "details",
    DetailsDotProduct = "details.product",
    DetailsDotWarehouse = "details.warehouse",
    Payments = "payments",
    PaymentDotTransaction = "payments.transaction",
    Tags = "tags",
    Sharings = "sharings",
    RecurrencePlan = "recurrence_plan",
    ActiveEDocument = "active_e_document",
}
