export enum ResourceType {
    SalesInvoices = "sales_invoices",
    ItemCategories = "item_categories",
    Contacts = "contacts",
    ContactPortals = "contact_portals",
    ContactPeople = "contact_people",
    SalesInvoiceDetails = "sales_invoice_details",
    Payments = "payments",
    Tags = "tags",
    SalesOffers = "sales_offers",
    Sharings = "sharings",
    RecurrencePlans = "recurrence_plans",
    EArchives = "e_archives",
    EInvoices = "e_invoices",
}
